//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanban.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kanban.src.View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Note:.
        /// </summary>
        public static string AboutControl_ReleaseNote {
            get {
                return ResourceManager.GetString("AboutControl_ReleaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to △ Individuals and interactions.
        /// </summary>
        public static string Agile_Manifesto1 {
            get {
                return ResourceManager.GetString("Agile_Manifesto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to △ Working software.
        /// </summary>
        public static string Agile_Manifesto2 {
            get {
                return ResourceManager.GetString("Agile_Manifesto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to △ Customer collaboration.
        /// </summary>
        public static string Agile_Manifesto3 {
            get {
                return ResourceManager.GetString("Agile_Manifesto3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to △ Responding to change.
        /// </summary>
        public static string Agile_Manifesto4 {
            get {
                return ResourceManager.GetString("Agile_Manifesto4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project description.
        /// </summary>
        public static string Board_DefaultDescription {
            get {
                return ResourceManager.GetString("Board_DefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        public static string Board_DefaultTitle {
            get {
                return ResourceManager.GetString("Board_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail：{0}.
        /// </summary>
        public static string Board_DetailFormat {
            get {
                return ResourceManager.GetString("Board_DetailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name：{0} .
        /// </summary>
        public static string Board_NameFormat {
            get {
                return ResourceManager.GetString("Board_NameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string BoardPage_BoardLabel {
            get {
                return ResourceManager.GetString("BoardPage_BoardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        public static string BoardPage_Filter {
            get {
                return ResourceManager.GetString("BoardPage_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created：{0:dd/MMM/yyyy}.
        /// </summary>
        public static string Card_CreateDateFormat {
            get {
                return ResourceManager.GetString("Card_CreateDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New work item.
        /// </summary>
        public static string Card_DefaultTitle {
            get {
                return ResourceManager.GetString("Card_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release：{0:dd/MMM/yyyy}.
        /// </summary>
        public static string Card_ReleaseDateFormat {
            get {
                return ResourceManager.GetString("Card_ReleaseDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible：.
        /// </summary>
        public static string Card_ResponsiblePerson {
            get {
                return ResourceManager.GetString("Card_ResponsiblePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Changed：{0:dd/MMM/yyyy}.
        /// </summary>
        public static string Card_StateChangedDateFormat {
            get {
                return ResourceManager.GetString("Card_StateChangedDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag：{0}.
        /// </summary>
        public static string Card_TagFormat {
            get {
                return ResourceManager.GetString("Card_TagFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item：{0}.
        /// </summary>
        public static string Card_WorkItemFormat {
            get {
                return ResourceManager.GetString("Card_WorkItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string CardEdit_Blocked {
            get {
                return ResourceManager.GetString("CardEdit_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work type：.
        /// </summary>
        public static string CardEdit_CardType {
            get {
                return ResourceManager.GetString("CardEdit_CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created：.
        /// </summary>
        public static string CardEdit_CreateDate {
            get {
                return ResourceManager.GetString("CardEdit_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description：.
        /// </summary>
        public static string CardEdit_Description {
            get {
                return ResourceManager.GetString("CardEdit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design overview :.
        /// </summary>
        public static string CardEdit_DesignOverview {
            get {
                return ResourceManager.GetString("CardEdit_DesignOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation：.
        /// </summary>
        public static string CardEdit_Estimation {
            get {
                return ResourceManager.GetString("CardEdit_Estimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled to release.
        /// </summary>
        public static string CardEdit_IsScheduledToRelease {
            get {
                return ResourceManager.GetString("CardEdit_IsScheduledToRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merged into major branch.
        /// </summary>
        public static string CardEdit_MergedIntoMajorBranch {
            get {
                return ResourceManager.GetString("CardEdit_MergedIntoMajorBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merged into master.
        /// </summary>
        public static string CardEdit_MergedIntoMaster {
            get {
                return ResourceManager.GetString("CardEdit_MergedIntoMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merged into master and major branch.
        /// </summary>
        public static string CardEdit_MergedIntoMasterAndMajorBranch {
            get {
                return ResourceManager.GetString("CardEdit_MergedIntoMasterAndMajorBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release：.
        /// </summary>
        public static string CardEdit_ReleaseDate {
            get {
                return ResourceManager.GetString("CardEdit_ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible：.
        /// </summary>
        public static string CardEdit_ResponsiblePerson {
            get {
                return ResourceManager.GetString("CardEdit_ResponsiblePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Changed：.
        /// </summary>
        public static string CardEdit_StateChanged {
            get {
                return ResourceManager.GetString("CardEdit_StateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of state changed.
        /// </summary>
        public static string CardEdit_StateChangedOfHistory {
            get {
                return ResourceManager.GetString("CardEdit_StateChangedOfHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work state change history：.
        /// </summary>
        public static string CardEdit_StateChangeHistory {
            get {
                return ResourceManager.GetString("CardEdit_StateChangeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string CardEdit_StateOfHistory {
            get {
                return ResourceManager.GetString("CardEdit_StateOfHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked or merged status.
        /// </summary>
        public static string CardEdit_StateOfHistoryBlockedOrMerged {
            get {
                return ResourceManager.GetString("CardEdit_StateOfHistoryBlockedOrMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story points：.
        /// </summary>
        public static string CardEdit_StoryPoints {
            get {
                return ResourceManager.GetString("CardEdit_StoryPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag：.
        /// </summary>
        public static string CardEdit_Tag {
            get {
                return ResourceManager.GetString("CardEdit_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test cases：.
        /// </summary>
        public static string CardEdit_TestCases {
            get {
                return ResourceManager.GetString("CardEdit_TestCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit work item.
        /// </summary>
        public static string CardEdit_Title {
            get {
                return ResourceManager.GetString("CardEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item：.
        /// </summary>
        public static string CardEdit_WorkItem {
            get {
                return ResourceManager.GetString("CardEdit_WorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work state：.
        /// </summary>
        public static string CardEdit_WorkState {
            get {
                return ResourceManager.GetString("CardEdit_WorkState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string CheckBoxSwitch_Off {
            get {
                return ResourceManager.GetString("CheckBoxSwitch_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string CheckBoxSwitch_On {
            get {
                return ResourceManager.GetString("CheckBoxSwitch_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string CheckBoxSwitch_ShowDetail {
            get {
                return ResourceManager.GetString("CheckBoxSwitch_ShowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline.
        /// </summary>
        public static string CheckBoxSwitch_ShowOutline {
            get {
                return ResourceManager.GetString("CheckBoxSwitch_ShowOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MMM/yyyy HH:mm.
        /// </summary>
        public static string DateTime_LongFormatter {
            get {
                return ResourceManager.GetString("DateTime_LongFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MMM.
        /// </summary>
        public static string DateTime_MonthDayFormatter {
            get {
                return ResourceManager.GetString("DateTime_MonthDayFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Database.
        /// </summary>
        public static string DropDB_Title {
            get {
                return ResourceManager.GetString("DropDB_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Kanban board is a work and workflow visualization tool that enables you to optimize the flow of your work..
        /// </summary>
        public static string Help_KanbanDescription {
            get {
                return ResourceManager.GetString("Help_KanbanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.Visualization.
        /// </summary>
        public static string Kanban_Practice1 {
            get {
                return ResourceManager.GetString("Kanban_Practice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.Limit WIP.
        /// </summary>
        public static string Kanban_Practice2 {
            get {
                return ResourceManager.GetString("Kanban_Practice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.Enhance Flow.
        /// </summary>
        public static string Kanban_Practice3 {
            get {
                return ResourceManager.GetString("Kanban_Practice3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.Feedback chain.
        /// </summary>
        public static string Kanban_Practice4 {
            get {
                return ResourceManager.GetString("Kanban_Practice4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.Evolving and improving.
        /// </summary>
        public static string Kanban_Practice5 {
            get {
                return ResourceManager.GetString("Kanban_Practice5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Cycle Time = Items of WIP / throughput.
        /// </summary>
        public static string Kanban_PracticeCycleTimeNote {
            get {
                return ResourceManager.GetString("Kanban_PracticeCycleTimeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practices.
        /// </summary>
        public static string Kanban_PracticeTitle {
            get {
                return ResourceManager.GetString("Kanban_PracticeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers(Seperate by semicolon):.
        /// </summary>
        public static string Main_Developers {
            get {
                return ResourceManager.GetString("Main_Developers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note of Kanban:.
        /// </summary>
        public static string Main_KanbanDetail {
            get {
                return ResourceManager.GetString("Main_KanbanDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Kanban:.
        /// </summary>
        public static string Main_KanbanName {
            get {
                return ResourceManager.GetString("Main_KanbanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process of this project.
        /// </summary>
        public static string Main_Process {
            get {
                return ResourceManager.GetString("Main_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanban.
        /// </summary>
        public static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really delete &lt;{0}&gt;?.
        /// </summary>
        public static string Message_DeleteComfirmQuesion {
            get {
                return ResourceManager.GetString("Message_DeleteComfirmQuesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comfirm to delete.
        /// </summary>
        public static string Message_DeleteComfirmTitle {
            get {
                return ResourceManager.GetString("Message_DeleteComfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed error.
        /// </summary>
        public static string Message_DeleteErrorTitle {
            get {
                return ResourceManager.GetString("Message_DeleteErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History of the process work activities will also be deleted.\n Do you really delete presss step &lt;{0}&gt;?.
        /// </summary>
        public static string Message_DeleteProcessStepComfirm {
            get {
                return ResourceManager.GetString("Message_DeleteProcessStepComfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The presss step &lt;{0}&gt; could not be deleted. It has active work items or the board has less than 3 process steps..
        /// </summary>
        public static string Message_DeleteProcessStepError {
            get {
                return ResourceManager.GetString("Message_DeleteProcessStepError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown story points exist in released item..
        /// </summary>
        public static string Message_HasUnknownStoryPointsInReleasedItem {
            get {
                return ResourceManager.GetString("Message_HasUnknownStoryPointsInReleasedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average cycle time: .
        /// </summary>
        public static string Metrics_AveCycleTime {
            get {
                return ResourceManager.GetString("Metrics_AveCycleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average throughput:.
        /// </summary>
        public static string Metrics_AveThroughput {
            get {
                return ResourceManager.GetString("Metrics_AveThroughput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ave WIP:.
        /// </summary>
        public static string Metrics_AveWIP {
            get {
                return ResourceManager.GetString("Metrics_AveWIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle time: .
        /// </summary>
        public static string Metrics_CycleTimeLabel {
            get {
                return ResourceManager.GetString("Metrics_CycleTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Metrics_DateLabel {
            get {
                return ResourceManager.GetString("Metrics_DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Days/Item.
        /// </summary>
        public static string Metrics_DaysPerItem {
            get {
                return ResourceManager.GetString("Metrics_DaysPerItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution(%).
        /// </summary>
        public static string Metrics_DistributionLabel {
            get {
                return ResourceManager.GetString("Metrics_DistributionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution.
        /// </summary>
        public static string Metrics_DistributionLabel1 {
            get {
                return ResourceManager.GetString("Metrics_DistributionLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Done cumulativ).
        /// </summary>
        public static string Metrics_DoneCumulative {
            get {
                return ResourceManager.GetString("Metrics_DoneCumulative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Items: .
        /// </summary>
        public static string Metrics_DoneItems {
            get {
                return ResourceManager.GetString("Metrics_DoneItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration of metrics:{0} days.
        /// </summary>
        public static string Metrics_DurationOfMetrics {
            get {
                return ResourceManager.GetString("Metrics_DurationOfMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated cycle time: .
        /// </summary>
        public static string Metrics_EstimatedCycleTime {
            get {
                return ResourceManager.GetString("Metrics_EstimatedCycleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to △Estimation too much: .
        /// </summary>
        public static string Metrics_EstimationMuch {
            get {
                return ResourceManager.GetString("Metrics_EstimationMuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ○Estimation proper: .
        /// </summary>
        public static string Metrics_EstimationProper {
            get {
                return ResourceManager.GetString("Metrics_EstimationProper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▽Estimation too small: .
        /// </summary>
        public static string Metrics_EstimationSmall {
            get {
                return ResourceManager.GetString("Metrics_EstimationSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Metrics_FormatLabelDate {
            get {
                return ResourceManager.GetString("Metrics_FormatLabelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Days.
        /// </summary>
        public static string Metrics_FormatLabelDay {
            get {
                return ResourceManager.GetString("Metrics_FormatLabelDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Metrics_ItemsLabel {
            get {
                return ResourceManager.GetString("Metrics_ItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked items.
        /// </summary>
        public static string Metrics_ItemsOfBlocked {
            get {
                return ResourceManager.GetString("Metrics_ItemsOfBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug fix items.
        /// </summary>
        public static string Metrics_ItemsOfBugfix {
            get {
                return ResourceManager.GetString("Metrics_ItemsOfBugfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average velocity for last 6 weeks: {0} / Two weeks.
        /// </summary>
        public static string Metrics_Last6WeeksAveVelocity {
            get {
                return ResourceManager.GetString("Metrics_Last6WeeksAveVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max WIP:.
        /// </summary>
        public static string Metrics_MaxWIP {
            get {
                return ResourceManager.GetString("Metrics_MaxWIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occured date:.
        /// </summary>
        public static string Metrics_OccuredDate {
            get {
                return ResourceManager.GetString("Metrics_OccuredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Week.
        /// </summary>
        public static string Metrics_PerWeek {
            get {
                return ResourceManager.GetString("Metrics_PerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story points.
        /// </summary>
        public static string Metrics_StoryPointsLabel {
            get {
                return ResourceManager.GetString("Metrics_StoryPointsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days:.
        /// </summary>
        public static string Metrics_TotalDate {
            get {
                return ResourceManager.GetString("Metrics_TotalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ∞ weeks.
        /// </summary>
        public static string Metrics_UnknownWeeks {
            get {
                return ResourceManager.GetString("Metrics_UnknownWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  weeks.
        /// </summary>
        public static string Metrics_Weeks {
            get {
                return ResourceManager.GetString("Metrics_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlog(Limit:∞).
        /// </summary>
        public static string Process_BackLogTitle {
            get {
                return ResourceManager.GetString("Process_BackLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development(Limit:5).
        /// </summary>
        public static string Process_DevelopmentTitle {
            get {
                return ResourceManager.GetString("Process_DevelopmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Process_DoneTitle {
            get {
                return ResourceManager.GetString("Process_DoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin of metrics.
        /// </summary>
        public static string Process_MetricsBegin {
            get {
                return ResourceManager.GetString("Process_MetricsBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of metrics.
        /// </summary>
        public static string Process_MetricsEnd {
            get {
                return ResourceManager.GetString("Process_MetricsEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewWork(Limit:1).
        /// </summary>
        public static string Process_NewProcessStepTitle {
            get {
                return ResourceManager.GetString("Process_NewProcessStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing.
        /// </summary>
        public static string Process_PreparingTitle {
            get {
                return ResourceManager.GetString("Process_PreparingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release(Limit:∞).
        /// </summary>
        public static string Process_ReleaseTitle {
            get {
                return ResourceManager.GetString("Process_ReleaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement(Limit:3).
        /// </summary>
        public static string Process_RequirementTitle {
            get {
                return ResourceManager.GetString("Process_RequirementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test(Limit:3).
        /// </summary>
        public static string Process_TestTitle {
            get {
                return ResourceManager.GetString("Process_TestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string Process_WIPTitle {
            get {
                return ResourceManager.GetString("Process_WIPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database:.
        /// </summary>
        public static string Setting_Database {
            get {
                return ResourceManager.GetString("Setting_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Setting_DBBackup {
            get {
                return ResourceManager.GetString("Setting_DBBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Setting_DBCancel_ToolTip {
            get {
                return ResourceManager.GetString("Setting_DBCancel_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder:.
        /// </summary>
        public static string Setting_DBFolder {
            get {
                return ResourceManager.GetString("Setting_DBFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information:.
        /// </summary>
        public static string Setting_DBInformation {
            get {
                return ResourceManager.GetString("Setting_DBInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Priority when restoring Kanban database.
        /// </summary>
        public static string Setting_DBPriority {
            get {
                return ResourceManager.GetString("Setting_DBPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Setting_DBRestore {
            get {
                return ResourceManager.GetString("Setting_DBRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop database.
        /// </summary>
        public static string Setting_DropDB {
            get {
                return ResourceManager.GetString("Setting_DropDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string Setting_Language {
            get {
                return ResourceManager.GetString("Setting_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language setting, DB backup.
        /// </summary>
        public static string Setting_Title {
            get {
                return ResourceManager.GetString("Setting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add board.
        /// </summary>
        public static string ToolTip_AddBoard {
            get {
                return ResourceManager.GetString("ToolTip_AddBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add card.
        /// </summary>
        public static string ToolTip_AddCard {
            get {
                return ResourceManager.GetString("ToolTip_AddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add process step.
        /// </summary>
        public static string ToolTip_AddProcessStep {
            get {
                return ResourceManager.GetString("ToolTip_AddProcessStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back board.
        /// </summary>
        public static string ToolTip_BoardBack {
            get {
                return ResourceManager.GetString("ToolTip_BoardBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front board.
        /// </summary>
        public static string ToolTip_BoardFront {
            get {
                return ResourceManager.GetString("ToolTip_BoardFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cards.
        /// </summary>
        public static string ToolTip_CardsCountImage {
            get {
                return ResourceManager.GetString("ToolTip_CardsCountImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total story points.
        /// </summary>
        public static string ToolTip_CardTotalPointsImage {
            get {
                return ResourceManager.GetString("ToolTip_CardTotalPointsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ToolTip_Delete {
            get {
                return ResourceManager.GetString("ToolTip_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ToolTip_Edit {
            get {
                return ResourceManager.GetString("ToolTip_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter to confirm(seperate keywords by white space or comma)
        ///Release date format is year month and day(e.g. 20191101、191101、1101).
        /// </summary>
        public static string ToolTip_Filtering {
            get {
                return ResourceManager.GetString("ToolTip_Filtering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string ToolTip_GotoSetting {
            get {
                return ResourceManager.GetString("ToolTip_GotoSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to back.
        /// </summary>
        public static string ToolTip_MoveToBack {
            get {
                return ResourceManager.GetString("ToolTip_MoveToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to front.
        /// </summary>
        public static string ToolTip_MoveToFront {
            get {
                return ResourceManager.GetString("ToolTip_MoveToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open board.
        /// </summary>
        public static string ToolTip_OpenBoard {
            get {
                return ResourceManager.GetString("ToolTip_OpenBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string ToolTip_Priority {
            get {
                return ResourceManager.GetString("ToolTip_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ToolTip_Refresh {
            get {
                return ResourceManager.GetString("ToolTip_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release note.
        /// </summary>
        public static string ToolTip_ReleaseNote {
            get {
                return ResourceManager.GetString("ToolTip_ReleaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replicate card.
        /// </summary>
        public static string ToolTip_ReplicateCard {
            get {
                return ResourceManager.GetString("ToolTip_ReplicateCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show detailed/outline of cards.
        /// </summary>
        public static string ToolTip_ShowCardDetailOrOutline {
            get {
                return ResourceManager.GetString("ToolTip_ShowCardDetailOrOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story point.
        /// </summary>
        public static string ToolTip_StoryPoints {
            get {
                return ResourceManager.GetString("ToolTip_StoryPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Large(more than 2 weeks).
        /// </summary>
        public static string ToolTip_StoryPoints_Extra_Large {
            get {
                return ResourceManager.GetString("ToolTip_StoryPoints_Extra_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large(within 2 weeks).
        /// </summary>
        public static string ToolTip_StoryPoints_Large {
            get {
                return ResourceManager.GetString("ToolTip_StoryPoints_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium(within 1 week).
        /// </summary>
        public static string ToolTip_StoryPoints_Medium {
            get {
                return ResourceManager.GetString("ToolTip_StoryPoints_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small(within 2 or 3 days).
        /// </summary>
        public static string ToolTip_StoryPoints_Small {
            get {
                return ResourceManager.GetString("ToolTip_StoryPoints_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown story points.
        /// </summary>
        public static string ToolTip_StoryPoints_Unknown {
            get {
                return ResourceManager.GetString("ToolTip_StoryPoints_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch front and back.
        /// </summary>
        public static string ToolTip_SwitchBoardFrontAndBack {
            get {
                return ResourceManager.GetString("ToolTip_SwitchBoardFrontAndBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worked Days.
        /// </summary>
        public static string ToolTip_WorkedDays {
            get {
                return ResourceManager.GetString("ToolTip_WorkedDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In/Zoom Out.
        /// </summary>
        public static string ToolTip_Zoom {
            get {
                return ResourceManager.GetString("ToolTip_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string View_Close {
            get {
                return ResourceManager.GetString("View_Close", resourceCulture);
            }
        }
    }
}
